language: ruby
rvm: 2.5.5
install: gem install asciidoctor-pdf
script: make
deploy:
  provider: releases
  api_key:
    secure: S+4mH91rDb7hyUXdkGjn4HU0Uz6PPyJK2tMrc728eGRTq0AJdP1Dg1ETopElZIdQPpYw72p0xuTkm3ZS3fh2GlHPIzKE0iC0YfGtGhbLIkfmkaCdCrgULceG1UOEeqGbjfyjIXj0CjZ/nJoc9H+1ghzZ+GKRSBiiBODo4wxrJTxLNyNrxlQRN6H8oyHIXZxjbaK5rJjZzfA1BzJyl1GXvlaGiRRbHMoR4GfsLK3XwmYJXljq/G/UKaETz9ZQuqlf+WYjILe7S5B7NARmL2ENJRouTbvx0nWB3I54/2oezzBpOdq3wm/Rchs/uunWGbWIt00PQHYoDv0s768DP092YBKOZhEpRSd6WfNwyIBclx4rWn/K43nS/Xmo02P1uJL9070pqjV7eWkdHZRh3VdvgMRj7rZpJAZgfzZdc69bXEBuOquRnyB3DbJdwpjmh77pxfXlplVjBfiBI+hHNrwcfJ41SvVpLNlpqlrNhJWZx+YhqSMAtERTf7maKogOI/UcrG/qD5DwyTCTEzYmkU2/9XAwlvVEheGv2/DnOPuad+ZnyZX9tKj+0Pi//Sc4bQVXhDEEKP4v6JF6UtHsso46V9Mr7kkQNSWLDvTkHnaW3KZ6D3kOg047+sAVFZ8GTVG/erIsy7kaYts5ECwuNgCfKTGHySbYqCVDr6KpxIpKYFw=
  file:
    - cv.pdf
    - cv.html
  skip_cleanup: true
  on:
    repo: davedoesdev/cv
    tags: true
    all_branches: true
