= David Halls
dahalls@gmail.com
:nofooter:

== Employment

Member of Technical Staff at Bromium::
  _September 2012 - Present_ +
Bromium uses micro-virtualisation to make endpoints trustworthy. I designed and 
implemented the following features: +
+
  * Site-to-VM placement logic
  * Certificates, smart cards
  * Authentication (SSPI)
  * Intranet detection
  * DOM storage
  * Download
+
Plus I wrote unit tests, fixed bugs and solved customer issues.
Most of this work was in C/C++ on Windows.

Senior Software Engineer at Citrix::
 _June 2009 - September 2012_ +
I moved to a new project within Citrix, XenClient (a client hypervisor): +
+
  * Implemented device and user authentication.
  * Added support for Active Directory users to XenClient Synchronizer (the server with which the client hypervisor communicates).
  * General troubleshooting for this fast-moving project.
  * Investigated how best to integrate XenClient with other Citrix products.
+
Most of this work was in C on Linux.

Research Engineer at Citrix::
_February 1999 - June 2009_ +
I started out researching new Web-based products and then moved onto adding
new features to core product: +
+
  * Implemented single sign-on to Citrix XenApp. This involved writing Windows logon components (GINA, credential provider, authentication package) and an ICA virtual channel.
  * Extended this to allow federated authentication to XenApp (using Microsoft ADFS).
  * Implemented a portable, simple WS-Federation security token service.
  * Prototyped cloud-based desktops, running on Amazon EC2 and brokered with Citrix software.
  * Enhanced Citrix Password Manager so it can run from a removable device.
  * Prototyped Web service versions of XenApp server components.
  * Carried out applied research into using server-based computing with dynamic HTML and mobile applications.
  * Worked on patent applications, 6 of which were issued.
+
This work was initially in Javascript and C#, then C/C++ on Windows.

Research Engineer at Persimmon IT::
_October 1997 - February 1999_ +
Persimmon IT designed websites. I was part of a team developing software to
transform XML into HTML using Standard ML (we began before the first XSL
working draft was published).

Intern at Matra Marconi Space Systems::
_June 1992 - September 1993_ +
This was a year out whilst an undergraduate. Responsibilities ranged from PC
maintenance to helping sort out the entry card database and writing image
processing code.

== Open Source

I've written and maintain a number of open source projects in these general
areas:

* Message routing and queueing
* Authentication, authorisation and cryptography
* Data transfer
* Linux distribution from scratch

Most of this work is in Javascript and Python.

I've also contributed to a wide range of other projects including Node.js core,
unikernels and a number of Node.js and Python modules.

Please see my https://github.com/davedoesdev[Github profile].

== Education

PhD in Computer Science::
  _University of Cambridge, 1994 - 1997_ +
  3 publications

BSc First Class Hons in Computer Science::
  _University of Southampton, 1990 - 1994_ +
  4 prizes

A Levels in Maths (A), Physics (A) and English \(C)::
  _Tideway Comprehensive, 1988 - 1990_
